default:
  - baseUrl: https://gitlab.example.com
upstreams:
  - baseUrl: https://registry.npmjs.org
    scopes:
      - jp.hoge.*
      - com.piyo.*
  - baseUrl: https://package.openupm.com
    scopes:
      - com.fuga.*
